# Copyright Yahoo. Licensed under the terms of the Apache 2.0 license. See LICENSE in the project root.

shared:
  image: vespaengine/vespa-pipeline:latest
  secrets:
    - DOCKER_HUB_DEPLOY_KEY

  environment:
    USER_SHELL_BIN: bash

  annotations:
    screwdriver.cd/cpu: HIGH
    screwdriver.cd/ram: HIGH
    screwdriver.cd/disk: HIGH
    screwdriver.cd/timeout: 60

    inspect: &inspect
      inspect: |
        set -x
        env | grep -v TOKEN
        cat /proc/cpuinfo
        cat /proc/meminfo
        df -h
        uname -a

    install-deps: &install-deps
      install-deps: |
        # Install the multi-arch support
        rm -f /usr/bin/qemu-*
        podman run --rm --cap-add SYS_ADMIN docker.io/multiarch/qemu-user-static --reset -p yes

    build: &build
      build: |
          IFS=',' read -r -a PARSED <<< "$CONTAINER_ARCH"
          PLATFORMS=$(for A in ${PARSED[@]}; do echo "linux/$A"; done | xargs | sed 's/\ /,/g')
          buildah bud \
            --file Dockerfile \
            --jobs 2  \
            --label "source_repo=$GIT_URL" \
            --label "source_ref=$GIT_COMMIT" \
            --label "build_url=$SD_BUILD_URL" \
            --layers=false \
            --manifest "$CONTAINER_IMAGE:$CONTAINER_TAG" \
            --platform $PLATFORMS \
            $CONTAINER_DIR

          buildah manifest inspect "$CONTAINER_IMAGE:$CONTAINER_TAG"

    publish: &publish
      publish: |
        if [[ -z $SD_PULL_REQUEST ]]; then
          set +x
          buildah login --username aressem --password "$DOCKER_HUB_DEPLOY_KEY" docker.io
          set -x

          buildah manifest push --all --format v2s2 "$CONTAINER_IMAGE:$CONTAINER_TAG" "docker://$CONTAINER_IMAGE:$CONTAINER_TAG"
        fi

    teardown-inspect: &teardown-inspect
      teardown-inspect: |
        buildah images
        df -h

    common-steps: &common-steps
      steps:
        - *inspect
        - *install-deps
        - *build
        - *publish
        - *teardown-inspect

jobs:
  publish-build-centos7:
    sourcePaths: ["screwdriver.yaml", "build/centos7/"]
    environment:
      CONTAINER_ARCH: "amd64"
      CONTAINER_DIR: 'build/centos7'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-centos7'
      CONTAINER_TAG: 'latest'
    <<: *common-steps

  publish-dev-centos7:
    sourcePaths: ["screwdriver.yaml", "dev/centos7/"]
    environment:
      CONTAINER_ARCH: "amd64"
      CONTAINER_DIR: 'dev/centos7'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-dev-centos7'
      CONTAINER_TAG: 'latest'
    <<: *common-steps

  publish-build-centos-stream8:
    sourcePaths: ["screwdriver.yaml", "build/centos-stream8/"]
    requires: [~pr, ~commit]
    environment:
      CONTAINER_ARCH: "amd64,arm64"
      CONTAINER_DIR: 'build/centos-stream8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-centos-stream8'
      CONTAINER_TAG: 'latest'
    <<: *common-steps

  publish-dev-centos-stream8:
    sourcePaths: ["screwdriver.yaml", "dev/centos-stream8/"]
    requires: [~pr, ~commit, ~publish-build-centos-stream8]
    environment:
      CONTAINER_ARCH: "amd64,arm64"
      CONTAINER_DIR: 'dev/centos-stream8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-dev-centos-stream8'
      CONTAINER_TAG: 'latest'
    <<: *common-steps

  publish-build-almalinux-8:
    sourcePaths: ["screwdriver.yaml", "build/almalinux-8/"]
    requires: [~pr, ~commit]
    environment:
      CONTAINER_ARCH: "amd64,arm64"
      CONTAINER_DIR: 'build/almalinux-8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-build-almalinux-8'
      CONTAINER_TAG: 'latest'
    <<: *common-steps

  publish-dev-almalinux-8:
    sourcePaths: ["screwdriver.yaml", "dev/almalinux-8/"]
    requires: [~pr, ~commit, ~publish-build-almalinux-8]
    environment:
      CONTAINER_ARCH: "amd64,arm64"
      CONTAINER_DIR: 'dev/almalinux-8'
      CONTAINER_IMAGE: 'docker.io/vespaengine/vespa-dev-almalinux-8'
      CONTAINER_TAG: 'latest'
    <<: *common-steps
